[package]
name = "protobuf-gen-extract"
version = "0.1.0"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["full"] }
syn_util = "0.4"
